In [3]:
import sys
sys.path.append('../')

%load_ext autoreload
%autoreload 2

In [4]:
import numpy as np
from collections import defaultdict
import trimesh
import pygalmesh

import scipy.spatial as spa

from rdkit import Chem
from Bio.PDB import get_surface, PDBParser, ShrakeRupley, PDBIO, Select
from Bio.PDB.PDBExceptions import PDBConstructionWarning

from pocket import *

In [5]:
pqr_file = "/home/boris/Data/BigBindCache/19gs_B_rec_out/19gs_B_rec_pockets.pqr"
pocket_dict = get_pockets(pqr_file)

In [22]:
lig_files = ['/home/boris/Data/BigBind/P09211/13gs_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/3n9j_eaa_lig.sdf', '/home/boris/Data/BigBind/P09211/3kmo_eaa_lig.sdf', '/home/boris/Data/BigBind/P09211/3pgt_gbx_lig.sdf', '/home/boris/Data/BigBind/P09211/12gs_0hh_lig.sdf', '/home/boris/Data/BigBind/P09211/4gss_gtx_lig.sdf', '/home/boris/Data/BigBind/P09211/1pgt_gtx_lig.sdf', '/home/boris/Data/BigBind/P09211/1gss_lee_lig.sdf', '/home/boris/Data/BigBind/P09211/2pgt_gpr_lig.sdf', '/home/boris/Data/BigBind/P09211/1zgn_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/4pgt_gbx_lig.sdf', '/home/boris/Data/BigBind/P09211/3dgq_eaa_lig.sdf', '/home/boris/Data/BigBind/P09211/5l6x_6sg_lig.sdf', '/home/boris/Data/BigBind/P09211/3csh_lz6_lig.sdf', '/home/boris/Data/BigBind/P09211/1aqx_gtd_lig.sdf', '/home/boris/Data/BigBind/P09211/1px6_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/3csj_cbl_lig.sdf', '/home/boris/Data/BigBind/P09211/1aqv_0hg_lig.sdf', '/home/boris/Data/BigBind/P09211/19gs_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/5djl_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/13gs_sas_lig.sdf', '/home/boris/Data/BigBind/P09211/3gus_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/20gs_cbd_lig.sdf', '/home/boris/Data/BigBind/P09211/2a2r_gsn_lig.sdf', '/home/boris/Data/BigBind/P09211/10gs_vww_lig.sdf', '/home/boris/Data/BigBind/P09211/18gs_gdn_lig.sdf', '/home/boris/Data/BigBind/P09211/5ddl_5au_lig.sdf', '/home/boris/Data/BigBind/P09211/5jcw_gvx_lig.sdf', '/home/boris/Data/BigBind/P09211/9gss_gtx_lig.sdf', '/home/boris/Data/BigBind/P09211/3gus_n11_lig.sdf', '/home/boris/Data/BigBind/P09211/3ie3_n11_lig.sdf', '/home/boris/Data/BigBind/P09211/19gs_bsp_lig.sdf', '/home/boris/Data/BigBind/P09211/3csi_lz6_lig.sdf', '/home/boris/Data/BigBind/P09211/1lbk_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/3ie3_gsh_lig.sdf', '/home/boris/Data/BigBind/P09211/2j9h_gtx_lig.sdf', '/home/boris/Data/BigBind/P09211/3kmo_gsh_lig.sdf']

In [81]:
ligs = [ next(Chem.SDMolSupplier(lf)) for lf in lig_files ]

In [82]:
lig_volume = SphereVolume.from_mols(ligs)

In [118]:
print(pocket_dict[1].get_bounding_box())
print(lig_volume.get_bounding_box())
print(lig_volume.get_union_bounding_box(pocket_dict[1]))
pocket_dict[1].intersect_volume(lig_volume)

(array([ 9.544, -1.766, -7.471]), array([32.455, 13.146, 14.469]))
(array([13.763, -4.088, 20.185]), array([31.464, 18.711, 39.613]))
(array([ 9.544, -4.088, -7.471]), array([32.455, 18.711, 39.613]))


0.0

In [9]:
p1 = pocket_dict[1]
p2 = pocket_dict[2]
print(p1.coords.shape, p2.coords.shape)
np.concatenate((p1.coords, p2.coords)).shape

(70, 3) (62, 3)


(132, 3)